Revenue =[380,290,129,233,18,2,392]
print("Welcome to USI Bakery!\nThis program calculates the total revenue generated by bread sales done by the CS Programmers in a week.")
for i in range(6):
    print("Day ",i+1,":",float(Revenue[i]))
print("\nTotal revenue for the week:", float(sum(Revenue)))
print("\nThank you for your purchase at USI Bakery!\nProgram created by Evan Schleter")